name: Contribution Snake (Red Team)

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Red Team Snake
        uses: Platane/snk@v3
        with:
          github_user_name: frharsh
          outputs: |
            dist/github-snake-redteam.svg?palette=github-dark&color_snake=#ff003c
            dist/github-snake-light.svg?palette=github-light

      - name: Publish Snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
